"""GitHub App client — authentication and PR comment utilities."""

from __future__ import annotations

import logging
from functools import lru_cache

from github import Auth, Github, GithubIntegration
from github.GithubException import GithubException

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Severity formatting
# ---------------------------------------------------------------------------

_SEVERITY_EMOJI: dict[str, str] = {
    "critical": "🔴",
    "warning": "🟡",
    "info": "🔵",
}

_SEVERITY_ORDER: dict[str, int] = {
    "critical": 0,
    "warning": 1,
    "info": 2,
}


# ---------------------------------------------------------------------------
# Comment formatter
# ---------------------------------------------------------------------------


def _format_review_comment(findings: list[dict]) -> str:
    """Render *findings* as a GitHub Markdown comment body.

    Structure
    ---------
    ## 🤖 AI Code Review
    ### Summary
    X issues found: Y critical, Z warnings, W info
    ### Issues
    | Severity | Category | Line | Message | Suggestion |
    |---|---|---|---|---|
    | 🔴 critical | complexity | 42 | … | … |
    """
    total = len(findings)
    critical_count = sum(1 for f in findings if f.get("severity") == "critical")
    warning_count = sum(1 for f in findings if f.get("severity") == "warning")
    info_count = sum(1 for f in findings if f.get("severity") == "info")

    lines: list[str] = [
        "## 🤖 AI Code Review",
        "",
        "### Summary",
        f"**{total} issue{'s' if total != 1 else ''} found:** "
        f"{critical_count} critical · {warning_count} "
        f"warning{'s' if warning_count != 1 else ''} · {info_count} info",
        "",
    ]

    if not findings:
        lines += ["### Issues", "", "_No issues detected. Great work! ✅_"]
        return "\n".join(lines)

    # Sort: critical first, then warning, then info
    sorted_findings = sorted(
        findings,
        key=lambda f: _SEVERITY_ORDER.get(f.get("severity", "info"), 2),
    )

    lines += [
        "### Issues",
        "",
        "| Severity | Category | Line | Message | Suggestion |",
        "|---|---|---|---|---|",
    ]

    for finding in sorted_findings:
        severity = finding.get("severity", "info")
        emoji = _SEVERITY_EMOJI.get(severity, "🔵")
        category = finding.get("category", "style").capitalize()
        line_no = finding.get("line_number")
        line_str = str(line_no) if line_no is not None else "—"

        # Escape pipe characters so they don't break the Markdown table
        message = str(finding.get("message", "")).replace("|", "\\|")
        suggestion = str(finding.get("suggestion", "")).replace("|", "\\|")

        lines.append(
            f"| {emoji} {severity} | {category} | {line_str} | {message} | {suggestion} |"
        )

    lines += [
        "",
        "---",
        "_Generated by [AI Code Review](https://github.com/apps/ai-code-review)_",
    ]
    return "\n".join(lines)


# ---------------------------------------------------------------------------
# Client
# ---------------------------------------------------------------------------


class GitHubClient:
    """Authenticated GitHub App client.

    Parameters
    ----------
    app_id:
        The GitHub App's numeric ID (as a string).
    private_key:
        The PEM-encoded RSA private key for the GitHub App.
    """

    def __init__(self, app_id: str, private_key: str) -> None:
        self._app_auth = Auth.AppAuth(
            app_id=int(app_id),
            private_key=private_key,
        )
        self._integration = GithubIntegration(auth=self._app_auth)
        logger.debug("GitHubClient initialised for app_id=%s", app_id)

    # ------------------------------------------------------------------
    # Installation resolution
    # ------------------------------------------------------------------

    @lru_cache(maxsize=128)  # noqa: B019 — safe: installations are long-lived
    def _get_installation_id(self, repo_name: str) -> int:
        """Return the installation ID for the given ``owner/repo`` string.

        Results are cached so repeated calls within a process lifetime don't
        hit the API more than once per repo.
        """
        owner, repo = repo_name.split("/", 1)
        installation = self._integration.get_repo_installation(owner, repo)
        return installation.id

    def get_installation_client(self, repo_name: str) -> Github:
        """Return an authenticated :class:`Github` instance scoped to the
        installation that has access to *repo_name*.

        Parameters
        ----------
        repo_name:
            Repository in ``owner/repo`` format.

        Returns
        -------
        Github
            A fully-authenticated PyGithub client for the installation.

        Raises
        ------
        GithubException
            If no installation is found for the repository.
        """
        installation_id = self._get_installation_id(repo_name)
        installation_auth = self._app_auth.get_installation_auth(installation_id)
        return Github(auth=installation_auth)

    # ------------------------------------------------------------------
    # Review comment
    # ------------------------------------------------------------------

    def post_review_comment(
        self,
        repo_name: str,
        pr_number: int,
        findings: list[dict],
    ) -> None:
        """Post a formatted AI code review comment on a pull request.

        Parameters
        ----------
        repo_name:
            Repository in ``owner/repo`` format.
        pr_number:
            The pull request number to comment on.
        findings:
            List of issue dicts as returned by :class:`CodeQualityAgent`.
            Each dict must contain: ``severity``, ``category``,
            ``line_number`` (int or None), ``message``, ``suggestion``.

        Raises
        ------
        GithubException
            Propagated from PyGithub if the API call fails.
        ValueError
            If *repo_name* is not in ``owner/repo`` format.
        """
        if "/" not in repo_name:
            raise ValueError(
                f"repo_name must be in 'owner/repo' format, got: {repo_name!r}"
            )

        body = _format_review_comment(findings)

        try:
            gh = self.get_installation_client(repo_name)
            repo = gh.get_repo(repo_name)
            pull = repo.get_pull(pr_number)
            comment = pull.create_issue_comment(body)
            logger.info(
                "Posted review comment on %s#%d (comment id=%d, findings=%d)",
                repo_name,
                pr_number,
                comment.id,
                len(findings),
            )
        except GithubException as exc:
            logger.error(
                "Failed to post review comment on %s#%d: %s",
                repo_name,
                pr_number,
                exc,
            )
            raise
